version: 0.1.{build}

# branches:
#   only:
#     - master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

build:
  project: CSIntelPerfLibs.sln

after_test:
  - ps: .\nuget\pack.ps1

artifacts:
  - path: CSIntelPerfLibs\CSIntel.Ipp\bin\Release\CSIntel.Ipp.dll
    name: CSIntel.Ipp.dll
  - path: CSIntelPerfLibs\CSIntel.Mkl\bin\Release\CSIntel.Mkl.dll
    name: CSIntel.Mkl.dll    
  - path: '**\*.nupkg'

# deploy:
#   provider: NuGet
#   api_key:
#     secure: 
#   artifact: /.*\.nupkg/
