version: 0.1.{build}

# branches:
#   only:
#     - master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

platform: x6 4na 

configuration: Release

build:
  project: CSIntelPerfLibs.sln
  publish_nuget: true 
  include_nuget_references: true

# after_test:
#   - ps: .\nuget\pack.ps1

artifacts:
  - path: CSIntelPerfLibs\CSIntel.Ipp\bin\$(configuration)
    name: CSIntel.Ipp.dll
  - path: CSIntelPerfLibs\CSIntel.Mkl\bin\$(configuration)
    name: CSIntel.Mkl.dll    
  - path: '**\*.nupkg'

# deploy:
#   provider: NuGet
#   api_key:
#     secure: 
#   artifact: /.*\.nupkg/
