version: 0.1.{build}

# branches:
#   only:
#     - master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

#---------------------------------#
#       build configuration       #
#---------------------------------#
configuration: Release

build:
  project: CSIntelPerfLibs.sln
  publish_nuget: true 

before_build:
- ps: nuget restore

after_build:
  - ps: .\pack.ps1
#---------------------------------#
#       tests configuration       #
#---------------------------------#
test: off


#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
artifacts:
  - path: CSIntel.Ipp\bin\$(configuration)\CSIntel.Ipp.dll
    name: CSIntel.Ipp.dll
  - path: CSIntel.Mkl\bin\$(configuration)\CSIntel.Mkl.dll
    name: CSIntel.Mkl.dll    
  - path: '**\CSIntelPerfLibs*.nupkg'

#---------------------------------#
#     deployment configuration    #
#---------------------------------#
# deploy:
#   provider: NuGet
#   api_key:
#     secure: 
#   artifact: /.*\.nupkg/
